repos:
- repo: https://github.com/golangci/golangci-lint
  rev: v2.8.0
  hooks:
  - id: golangci-lint
    entry: golangci-lint run
    args:
    - --max-issues-per-linter=0
    - --max-same-issues=0
    #- --config=.code_quality/.golangci.yml
    - --new-from-rev=HEAD~1

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.16.0
  hooks:
  - id: pretty-format-golang
    args:
    - --autofix

